spring.config.activate.on-profile=local
spring.application.name=work-app
spring.datasource.url=jdbc:h2:mem:flowable-local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
flowableplus.work.runtime.database-schema-update=create-drop