spring.config.activate.on-profile=local
spring.application.name=work-app
server.port=8081

spring.datasource.url=${WORK_DB_URL:jdbc:postgresql://localhost:5432/flowableplus_work?currentSchema=flowable_local}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${WORK_DB_USERNAME:flowableplus}
spring.datasource.password=${WORK_DB_PASSWORD:flowableplus-dev}
spring.jpa.hibernate.ddl-auto=update

flowable.database-schema-update=true
flowableplus.work.runtime.database-schema-update=update